baseURL = "https://www.prashanttiwari.dev/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Prashant Tiwari - Prashant Tiwari"
    description = "Description"
    copyright = "Powered by Hugo & based on Aafu"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "light"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Prashant Tiwari,"
		tagline = "Senior DevOps Engineer,"
		location = "Remote"
        photo = "my_profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://linkedin.com/in/prashant0085/"
            title = "LinkedIn"
        [[params.social.list]]
            class = "fab"
            icon = "fa-stack-overflow"
            url = "https://stackoverflow.com/users/8161460/prashant-tiwari"
            title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/prashant0085"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "https://twitter.com/prashant0085"
            title = "Twitter"
	#[[params.social.list]]
        #    class = "ai"
        #    icon = "ai-google-scholar"
        #    url = "#"
        #    title = "Google Scholar"
	#[[params.social.list]]
        #    class = "ai"
        #    icon = "ai-researchgate"
        #    url = "#"
        #    title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "A fulltime remote senior DevOps engineer with nearly 6 years' experience working with Pipelines, CI/CD, Cloud, Containers and Agile methodologies Scrum/Scrumban/Kanban. | 3x AWS certified."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Senior DevOps Engineer"
            dates = "**Sep** **2020** - **Present**"
            link = "http://www.flux7.com/"
            company = "Flux7 Labs Inc."
            details = ""
        [[params.experience.list]]
            position = "DevOps Engineer"
            dates = "**Mar** **2019** - **Aug** **2020**"
            link = "http://www.flux7.com/"
            company = "Flux7 Labs Inc."
            details = "* Deploying Microservices with AWS Fargate with complete infrastructure automation using Terraform.\n * Deploying fast and secure CIS compliant AWS platforms for enterprises allowing them to start within 10 days.\n * Setting up ETL data engineering automation with AWS Glue, S3, Redshift, and Cloudwatch.\n * Deploying automated serverless nightly builds with AWS Lambda. Setting up monitoring, alarm and logging system for multi-account AWS environments."
        [[params.experience.list]]
            position = "DevOps Engineer"
            dates = "**Jan** **2017** - **Feb** **2019**"
            link = "https://expleogroup.com/"
            company = "Expleo Group"
            details = "* Building complete CI pipeline using Jenkins and GitHub. Using IaC (CloudFormation & Terraform) to build AWS infrastructure and provide software development and production platform.\n * Creating and maintaining Ansible playbooks with multiple roles.\n * Basic system administration and troubleshooting Red Hat based Linux systems.\n * Worked with build automation tools such as ANT in CI pipelines."
        [[params.experience.list]]
            position = "Test Engineer"
            dates = "**Mar** **2015** - **Dec** **2016**"
            link = "https://sqs.com/"
            company = "SQS India Infosystem Pvt Ltd"
            details = "* Monitoring health check of application and server by Performance testing tools and Nagios.\n * Creating and Maintaining Automation scripts used for performance testing.\n * Testing and raising defects for improvement in average response time and better throughput of servers."

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        #[[params.education.list]]
        #    degree = "Ph.D. in Subject"
        #    college = "University of State-City"
        #    dates = "2013 - 2018"
        #    thesis_title = "Effect of humans on other humans: a study of human behavior."
        #    thesis_link = "#"
        #[[params.education.list]]
        #    degree = "M.S. in Subject"
        #    college = "University of State-City"
        #    dates = "2013 - 2018"
        #    thesis_title = "Effect of humans on other humans: a study of human behavior."
        #    thesis_link = "#"
        [[params.education.list]]
            degree = "PG Diploma in Advanced Computing"
            college = "Centre for Development of Advanced Computing, Pune"
            dates = "2014 - 2015"
        [[params.education.list]]
            degree = "BE in Electronics"
            college = "Mumbai University"
            dates = "2009 - 2014"

    # Publication section
    #[params.publication]
    #    title = "Publications"
    #    icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
    #    format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
    #    types = ["Journal Articles", "Proceedings"]

    #    [[params.publication.list]]
    #        title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    #        authors = "F Last, F Second, P secondary"
    #        date = "2018"
    #        journal = "Journal of Field 52 (16), 9033-9044"
    #        link = "#"
    #        type = "Journal Articles"

    #    [[params.publication.list]]
    #        title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    #        authors = "F Last, F Second, P secondary"
    #        date = "2018"
    #        journal = "Journal of Field 52 (16), 9033-9044"
    #        link = "#"
    #        type = "Journal Articles"

    #    [[params.publication.list]]
    #        title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    #        authors = "F Last, F Second, P secondary"
    #        date = "2018"
    #        journal = "Journal of Field 52 (16), 9033-9044"
    #        link = "#"
    #        type = "Proceedings"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Terraform, AWS, Ansible, Python, Bash, Jenkins, Gitlab-ci, GitHub Actions"
            skillrating = 90
        [[params.skill.list]]
            skill = "Docker, Concourse, Prometheus, Grafana, Serverless"
            skillrating = 80
        [[params.skill.list]]
            skill = "Golang, Groovy, Kubernetes, Jira-server, Confluence-server, Jfrog Artifactory"
            skillrating = 70

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
		    hobby = "Cycling"
        [[params.hobby.list]]
		    hobby = "Football"
        [[params.hobby.list]]
		    hobby = "Cooking"
